// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Bagas Ramadhan Rusnadi",
            "email": "bagasramadhan239@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Endpoint untuk login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ServerError"
                        }
                    }
                }
            }
        },
        "/groups": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User membuat grup baru dan otomatis menjadi owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Membuat Group Baru",
                "parameters": [
                    {
                        "description": "Data Group (Minimal 1 member)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GroupInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.GroupResponse"
                        }
                    },
                    "400": {
                        "description": "Error validasi / ID member salah",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Token tidak valid",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.GroupInput": {
            "type": "object",
            "required": [
                "group_type",
                "members",
                "name"
            ],
            "properties": {
                "group_type": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.GroupResponse": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.MemberResponse"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controllers.InputRegisterValid": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 5,
                    "example": "john123"
                },
                "username": {
                    "type": "string",
                    "minLength": 5,
                    "example": "johndoe"
                }
            }
        },
        "controllers.LoginError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Record Not Found"
                },
                "message": {
                    "type": "string",
                    "example": "Email atau Password Salah"
                }
            }
        },
        "controllers.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "username@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 5,
                    "example": "password"
                }
            }
        },
        "controllers.LoginSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Login Success"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njk4MTE0NTIsInJvbGUiOjMsInVzZXJfaWQiOiJkN"
                }
            }
        },
        "controllers.MemberResponse": {
            "type": "object",
            "properties": {
                "member_id": {
                    "type": "string"
                },
                "role": {
                    "description": "Kita pake string (Owner/Member) bukan angka",
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/controllers.UserResponse"
                }
            }
        },
        "controllers.RegisterFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Email atau Username sudah terdaftar"
                }
            }
        },
        "controllers.RegisterSuccess": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/controllers.UserResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Register Berhasil"
                }
            }
        },
        "controllers.ServerError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Server Error"
                }
            }
        },
        "controllers.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-06-30T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "role_text": {
                    "type": "string",
                    "example": "User"
                },
                "subscription_exp": {
                    "type": "string",
                    "example": "2023-06-30T00:00:00Z"
                },
                "subscription_plan": {
                    "type": "string",
                    "example": "free"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-06-30T00:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "a0b1c2d3-e4f5-g6h7-i8j9-k0l1m2n3"
                },
                "user_role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserRole"
                        }
                    ],
                    "example": 3
                },
                "username": {
                    "type": "string",
                    "example": "JohnDoe"
                },
                "wallet": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.WalletResponse"
                    }
                }
            }
        },
        "controllers.WalletResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number",
                    "example": 100000
                },
                "currency": {
                    "type": "string",
                    "example": "IDR"
                },
                "wallet_id": {
                    "type": "string",
                    "example": "a0b1c2d3-e4f5-g6h7-i8j9-k0l1m2n3"
                },
                "wallet_name": {
                    "type": "string",
                    "example": "wallet1"
                }
            }
        },
        "models.UserRole": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "UserAdmin": "Bisa atur user",
                "UserDefault": "Pengguna aplikasi",
                "UserOwner": "Dewa"
            },
            "x-enum-descriptions": [
                "Dewa",
                "Bisa atur user",
                "Pengguna aplikasi"
            ],
            "x-enum-varnames": [
                "UserOwner",
                "UserAdmin",
                "UserDefault"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: \"Bearer \u003ctoken_jwt_disini\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Cashflow API Documentation",
	Description:      "Dokumentasi API untuk aplikasi Cashflow.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
